  
name: startup_namer
description: A startup-namer app.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

# #docregion dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  english_words: ^4.0.0-0
# #enddocregion dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0

flutter:
  uses-material-design: true